name: "Postman Newman Tests"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # smoke-tests:
  #   name: Run Smoke Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2.3.1

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2.3.1
  #       with:
  #         node-version: '16'

  #     - name: Install Newman and HTMLExtra Reporter
  #       run: |
  #         npm install -g newman
  #         npm install -g newman-reporter-htmlextra

  #     - name: Create results folder
  #       run: mkdir -p testResults

  #     - name: Run Smoke Tests
  #       run: |
  #         newman run restful_booker_bvt.postman_collection.json \
  #         -e Production.postman_environment.json \
  #         -r htmlextra \
  #         --reporter-htmlextra-export testResults/smoke-report.html \
  #         --name "[Smoke]Get All Bookings"

  regression-tests:
    name: Run Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Set up Node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: '16'

      - name: Install Newman and HTMLExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create results folder
        run: mkdir -p testResults

      - name: Run Full Regression Tests
        run: |
          newman run restful_booker_bvt.postman_collection.json \
          -e Production.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export testResults/regression-report.html
