name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Smoke Tests
        run: |
          newman run restful_booker_bvt.postman_collection.json \
          -e production.json \
          --reporters cli,html \
          --reporter-html-export reports/smoke-report.html \
          --folder "[Smoke]"

      - name: Upload Smoke Report
        uses: actions/upload-artifact@v3
        with:
          name: smoke-report
          path: reports/smoke-report.html

  full-tests:
    name: Run Full Test Suite
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Full Tests
        run: |
          newman run restful_booker_bvt.postman_collection.json \
          -e production.json \
          --reporters cli,html \
          --reporter-html-export reports/full-report.html

      - name: Upload Full Report
        uses: actions/upload-artifact@v3
        with:
          name: full-report
          path: reports/full-report.html
